# Generated by Django 3.1.5 on 2022-04-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_customuser_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='highest_streak',
            field=models.IntegerField(default=0),
        ),
    ]
